server:
  port: 10010
spring:
  application:
    name: gateway #网关服务的名称
  cloud:
    nacos:
      server-addr: localhost:8848 #配置nacos服务地址
    gateway:
      routes: #配置路由
        - id: user-service #路由的唯一id
          uri: lb://userservice #lb负载均衡，服务在nacos中的地址
          predicates:
            - Path=/user/** #路由断言，请求路径满足这个的会去被分配去访问这个路由
        - id: liveroom-service
          uri: lb://liveroomservice
          predicates:
            - Path=/liveRoom/**,/studyRoom/**
        - id: storage-service #存储服务，该路由的唯一id
          uri: lb://storageservice #lb使用负载均衡,后跟应用名
          predicates:
            - Path=/storage/** #请求断言，这个类型的访问路径推送到这个路由
        - id: interaction-service #交互服务
          uri: lb://interactionservice #负载均衡，从nacos那里获取服务
          predicates:
            - Path=/interaction/** #根据该路径去匹配该路由
        - id: search-service #搜素服务
          uri: lb://searchservice #负载均衡，从nacos那里拉取服务
          predicates:
            - Path=/search/** #路径匹配
      globalcors:  #解决跨域问题
        add-to-simple-url-handler-mapping: true   #允许浏览器的options访问行为
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"    #允许那些网址进行跨域请求
            allowedMethods: #允许进行跨域的方法
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" #允许的请求头，所有请求头
            allowCredentials: true #允许请求携带cookies
            maxAge: 360000 #这次跨域请求的有效期


  datasource: #配置数据库
    druid:
      url: jdbc:mysql://175.178.85.36:3306/zhibo
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
